
# Disable this on production
# local_backend: true

# Overview: https://decapcms.org/docs/backends-overview/
# Github: https://decapcms.org/docs/github-backend/
backend:
  name: github
  repo: RickBarretto/ecompjr-labelu
  branch: main


# === Localization settings

locale: pt


# === Files & Media configuration

# Stored files
media_folder: "src/assets/images"
# Uploaded media
public_folder: "src/assets/images"


# === Content collections configuration

# Collections: https://decapcms.org/docs/collection-folder/
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true 
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Rating (scale of 1-5)", name: "rating", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "pesquisadores"
    label: "Pesquisadores"
    folder: "src/content/pesquisadores"
    create: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "researcher" }
      - { label: "Nome completo", name: "name", widget: "string" }
      - { label: "Cargo no laboratório", name: "position", widget: "string", required: false }
      - label: "Nível acadêmico"
        name: "academicLevel"
        widget: "select"
        options:
          - { label: "Graduação", value: "Graduação" }
          - { label: "Mestrado", value: "Mestrado" }
          - { label: "Doutorado", value: "Doutorado" }
          - { label: "Pós-doutorado", value: "Pós-doutorado" }
          - { label: "Outro", value: "Outro" }
      - { label: "Lattes", name: "lattes", widget: "string" }
      - { label: "ORCID", name: "orcid", widget: "string", required: false }
      - { label: "LinkedIn", name: "linkedin", widget: "string", required: false }
      - { label: "Resumo", name: "summary", widget: "text" }
